repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: uv run --active black
        language: system
        types: [ python ]
        pass_filenames: true
      - id: isort
        name: isort
        entry: uv run --active isort
        language: system
        types: [ python ]
        pass_filenames: true
      - id: ruff
        name: ruff
        entry: uv run --active ruff format
        language: system
        types: [ python ]
        pass_filenames: true
      - id: mypy
        name: mypy
        entry: uv run --active mypy
        language: system
        types: [ python ]
        pass_filenames: true
        exclude: ^research/
